ALTER SESSION SET NLS_TIMESTAMP_FORMAT = "DD/MM/YYYY HH24:MI:SS.FF";

DROP TABLE Send_Message CASCADE CONSTRAINTS PURGE;
DROP TABLE Win CASCADE CONSTRAINTS PURGE;
DROP TABLE Kill CASCADE CONSTRAINTS PURGE;
DROP TABLE TR CASCADE CONSTRAINTS PURGE;
DROP TABLE CT CASCADE CONSTRAINTS PURGE;
DROP TABLE Itens CASCADE CONSTRAINTS PURGE;
DROP TABLE Championships CASCADE CONSTRAINTS PURGE;
DROP TABLE Prizes CASCADE CONSTRAINTS PURGE;
DROP TABLE Cellphones CASCADE CONSTRAINTS PURGE;
DROP TABLE Players CASCADE CONSTRAINTS PURGE;
DROP TABLE Team CASCADE CONSTRAINTS PURGE;
DROP TABLE Coach CASCADE CONSTRAINTS PURGE;